language: java

os:
   - linux

jdk:
   - oraclejdk8

sudo: false

cache:
   directories:
     - $HOME/.m2

install: /bin/true

script: mvn clean integration-test

branches:
   only:
      - master

notifications:
   email: false
