server:
  port: 20170

jasypt:
    encryptor:
        algorithm: PBEWITHMD5ANDDES
        password: ${APP_ENCRYPTION_PASSWORD:}
        keyObtentionIterations: 1000
        poolSize: 1
        providerName: SunJCE
        saltGeneratorClassname: org.jasypt.salt.RandomSaltGenerator
        stringOutputType: base64
        proxyPropertySources: false

origins:
    b2oplus: http://b2oplus.org

#graceful ascii banner